LR_scheduler: OneCycleLR
LR_scheduler_params:
  epochs: 10
  max_lr: 1e-2
  pct_start: 0.3
  steps_per_epoch: 1027
backbone: efficientnet_b0
batch_size: 64
data_dir: "/content/drive/MyDrive/DL\u57FA\u790E\u8B1B\u5EA7/\u6700\u7D42\u8AB2\u984C\
  /data"
device: cuda
early_stopping_rounds: 5
epochs: 10
expname: Effnet0b
lr: 1e-3
model_path: null
model_save_dir: null
num_classes: 1854
num_splits: 5
num_workers: 4
seed: 1234
use_wandb: false
ver: 1
