batch_size: 64
epochs: 15
lr: 1e-3
num_splits: 5
early_stopping_rounds: 3
num_classes: 1854

expname: Effnet0b
ver: 1

backbone: efficientnet_b0

LR_scheduler: OneCycleLR
LR_scheduler_params:
  max_lr: 1e-2
  steps_per_epoch: 1027
  epochs: 15
  pct_start: 0.3

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: '/content/drive/MyDrive/DL基礎講座/最終課題/data' #data
model_save_dir: 

# Evaluation
model_path: 