#CV: 0.03224, LB: 0.03049

batch_size: 64
epochs: 15
lr: 1e-3
early_stopping_rounds: 3
num_classes: 1854

aux_loss_ratio: 0.6 
dropout_rate: 0.1

expname: Effnet0b_holdout_aux_dropout
ver: 1

backbone: tf_efficientnet_b0.ns_jft_in1k

LR_scheduler: CosineAnnealingWarmRestarts
LR_scheduler_params:
  num_warmup_steps: 100
  num_training_steps: 15405

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: '/content/drive/MyDrive/DL基礎講座/最終課題/data' #data

# Evaluation
model_path: 