# CV: 0.03506 LB: ???

batch_size: 32
epochs: 10
lr: 1e-3
early_stopping_rounds: 3
num_classes: 1854

aux_loss_ratio: 0.6 
dropout_rate: 0.05

expname: Effnet2b_holdout_aux_dropout
ver: 1

backbone: tf_efficientnet_b2.ns_jft_in1k

LR_scheduler: CosineAnnealingWarmRestarts
LR_scheduler_params:
  num_warmup_steps: 2054
  num_training_steps: 2054 * 10

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: '/content/drive/MyDrive/DL基礎講座/最終課題/data' #data

# Evaluation
model_path: 